### ISSUE TITLE
Quality of Life issues

### ISSUE THREAD

**Issue by AndyGJorgensen** [KingLycosa/acnhpoker#4]
Things that would be nice to have

1 Disconnect from connected switch
2 Change or use last IP address used or even better ability to save a few IP addresses
3 Be able to refresh inventory after the player picks up items
4 Delete/Clear item slot

**Comment by yakobie** [comment]
These are very good ideas :) I'll start working on them soon.

**Comment by lsfgrd** [comment]
Hey, @KingLycosa are you accepting PRs? I would love to try and implement some of those things! Specially item 2 since I want it too. If you want some help  just @ me :D

**Comment by alec2dabreen** [comment]
Possible to spawn DIY recipes from this list?
https://pastebin.com/w8CVN7Zr

**Comment by ashundefined** [comment]
@alec2dabreen Well yes, but actually no. You can spawn recipes with a two-digit recipe-value if you first convert the hex recipe value from the list to dec and enter the dec value into the amount textbox (while using 16A2 as item id, of course).
For now, I'd not recommend it, however. I'm sure the maintainer will add support for recipes in the near future.

**Comment by yakobie** [comment]
I have added all of the initial requests in this issue excluding the first. I don't think it is something worth me rewriting a good bit of code over ATM. Currently the best way to disconnect is to close the program and reopen (hillbilly fix, I know).
