### ISSUE TITLE
Update Item List

### ISSUE THREAD

**Issue by SquirrelKiev** [KingLycosa/acnhpoker#6]
Some items are missing, e.g. rugs. 
A more complete list can be found here: https://github.com/Cuyler36/MyHorizons/blob/master/MyHorizons/Resources/v1/Text/Items/ItemNames_en.txt

**Comment by yakobie** [comment]
You can rename and reorganize the list I use with the program by simply editing the csv file, I am not interested in adding this list as it seems to just be item variants which you can already achieve with changing quantities.

**Comment by SquirrelKiev** [comment]
It’s not the item variations I’m talking about. It’s that the list is missing rugs.
