### ISSUE TITLE
Could not connect to the botbase server

### ISSUE THREAD

**Issue by GitYu2016** [KingLycosa/acnhpoker#7]
"Connect", then alert "Could not connect to the botbase server. " I don't know why this happening and how to fix it.please give me some suggestion. does it must connect WIFI?

**Comment by SquirrelKiev** [comment]
Yes. It connects to a botbase server which runs on your switch. Botbase can be found here: https://github.com/olliz0r/sys-botbase

**Comment by GitYu2016** [comment]
I connected WIFI. It works when I changed the IP according to IP in switch. yes! PC's Poker display items.  But  after I spawn item, ACNH's bag have not changed.
And Im using a hacked switch, so I think I cant turn ACNH off and back to switch desktop, it will download update.
