### ISSUE TITLE
Something happen with 1.1.4

### ISSUE THREAD

**Issue by GitYu2016** [KingLycosa/acnhpoker#8]
My ACNH Version is 1.1.4.
After I  spawn item, the bag I choosen been cleared. and Item is not been spawed.

Thank you very much for everything you have done!

**Comment by ashundefined** [comment]
In order to help you, more details are required.
Because the editor works just fine with ACNH 1.1.4a.

1. Which firmware version are you using?
1. Which sys-botbase version are you using?
1. Which CFW are you using?
1. Can you see your **whole** inventory once connected?

**Comment by GitYu2016** [comment]
1. firmware is 9.2.0
2. sys-botbase version is 1.4
3. CFW is 0.10.5
4. Can see whole inventory once connected. Just spawn item cannot see on switchACNH.
Maybe sys-botbase is not tested on Atmosphere (0.10.5). Maybe is I need to wait for update.

Big thank for your help.

**Comment by ashundefined** [comment]
Try using this build of sys-botbase:
https://github.com/olliz0r/sys-botbase/files/4472143/exefs.zip

This seems to fix issues with Atmosphere 0.10.5.
Just replace your sys-botbase `exefs.nsp` with the one from the archive.

Another potential source for problems seems to be Edizon (in some cases).
If you have Edizon installed as a tesla overlay, try removing that too.
(If you have no idea what I'm talking about, just ignore that part.)
